#!/bin/bash
RXB=0
for rxbytes in /sys/class/net/*/statistics/rx_bytes ; do
  let RXB+=$(<$rxbytes)
done

sleep 2

RXBN=0
for rxbytes in /sys/class/net/*/statistics/rx_bytes ; do
  let RXBN+=$(<$rxbytes)
done
#divide by two for the period, multiply by 10 to allow a correct decimal place
RXDIF=$(echo $(((RXBN - RXB) * 5  )))

SPEEDD="vB/s"
if [ $RXDIF -ge 10240 ]; then
	SPEEDD="vKi/s"
	RXDIF=$(echo $((RXDIF / 10240 )) )
fi

if [ $RXDIF -ge 10240 ]; then
	SPEEDD="vMi/s"
	RXDIF=$(echo $((RXDIF / 10240 )) )
fi

if [ $RXDIF -ge 10240 ]; then
	SPEEDD="vGi/s"
	RXDIF=$(echo $((RXDIF / 10240 )) )
fi

RXDIFF=$(($RXDIF % 10 ))
RXDIFI=$(( $RXDIF / 10 ))
RXDIF=$( echo  "$RXDIFI.$RXDIFF" )


echo "$RXDIF $SPEEDD"

